# Generated by Django 6.0 on 2025-12-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_purchase_purchaseitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="order_id",
            field=models.CharField(
                editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="order_id",
            field=models.CharField(
                editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
