# Generated by Django 4.2.27 on 2026-01-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_category_id_alter_customer_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Global total quantity'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price at the time of sale. 0 if transfer.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='action',
            field=models.CharField(choices=[('ADD', 'Stock Added'), ('REMOVE', 'Stock Removed'), ('SALE', 'Sold'), ('PURCHASE', 'Purchased'), ('ADJUST', 'Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In')], max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='destination_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_in', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='sale',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='sale',
            name='source_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_from', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='stocklog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.store'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.store')),
            ],
            options={
                'unique_together': {('store', 'product')},
            },
        ),
    ]
